Feature/config querybuilder kysely
Mentoria-CardsManagementApp/cards-managemente-app pull request #9
Opened 2024-03-27 02:24 UTC by herloncosta

## Describe your changes
Adicionei e configurei o query builder kysely e a lib pg, para automatizar a configuração das tabelas no PostgreSQL utilizando scripts.  

## How to test it
Criando e executando os scripts de migração e rollback.

## Pivotal Storie Id
https://www.pivotaltracker.com/n/projects/2697457/stories/187276123

## Type
- [ ] **Fix** - Fix an issue
- [ x ] **Feature** - Adds new feature
- [ ] **Style** - Visual changes
- [ ] **Hotfix** - Fix an urgent issue in PROD (the base branch should be **master**)
- [ ] **Refactor** - Refactor some part of the code

## Checklist before requesting a review
- [ x ] I have performed a self-review of my code

2024-03-28 01:47 UTC, MarioDoncel requested changes

2024-03-28 21:48 UTC, herloncosta commented on backend/api/src/database/postgres-dialect.ts
> +    max: 10,
Resolvido!

2024-03-28 21:56 UTC, herloncosta commented on backend/api/src/database/scripts/index.ts
Pensei em run-migrations e execute-migratios, mas migrations-runner fez mais sentido.

2024-03-30 15:32 UTC, MarioDoncel approved these changes

2024-03-30 15:32 UTC, merged